// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mkn_loglik_sparse_cpp
double mkn_loglik_sparse_cpp(int k, int n_tips, int n_internal, IntegerVector edge_parent, IntegerVector edge_child, NumericVector edge_length, IntegerVector qi, IntegerVector qj, NumericVector qx, NumericMatrix tip_states, int root_mode, NumericVector root_prior);
RcppExport SEXP _chromePlus_mkn_loglik_sparse_cpp(SEXP kSEXP, SEXP n_tipsSEXP, SEXP n_internalSEXP, SEXP edge_parentSEXP, SEXP edge_childSEXP, SEXP edge_lengthSEXP, SEXP qiSEXP, SEXP qjSEXP, SEXP qxSEXP, SEXP tip_statesSEXP, SEXP root_modeSEXP, SEXP root_priorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type n_tips(n_tipsSEXP);
    Rcpp::traits::input_parameter< int >::type n_internal(n_internalSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type edge_parent(edge_parentSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type edge_child(edge_childSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type edge_length(edge_lengthSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type qi(qiSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type qj(qjSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type qx(qxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type tip_states(tip_statesSEXP);
    Rcpp::traits::input_parameter< int >::type root_mode(root_modeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type root_prior(root_priorSEXP);
    rcpp_result_gen = Rcpp::wrap(mkn_loglik_sparse_cpp(k, n_tips, n_internal, edge_parent, edge_child, edge_length, qi, qj, qx, tip_states, root_mode, root_prior));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_chromePlus_mkn_loglik_sparse_cpp", (DL_FUNC) &_chromePlus_mkn_loglik_sparse_cpp, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_chromePlus(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
