# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mkn_loglik_sparse_cpp <- function(k, n_tips, n_internal, edge_parent, edge_child, edge_length, qi, qj, qx, tip_states, root_mode, root_prior) {
    .Call(`_chromePlus_mkn_loglik_sparse_cpp`, k, n_tips, n_internal, edge_parent, edge_child, edge_length, qi, qj, qx, tip_states, root_mode, root_prior)
}

